In [1]:
pip install numpy

In [1]:
import numpy as np

In [11]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
type(a)

numpy.ndarray

In [8]:
b=np.array(('a','b','c','d'))

In [10]:
a=10
type(a)

int

In [9]:
b

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [6]:
a

array([1, 2, 3, 4])

In [16]:
c=np.array([1,2,3,4],dtype='int')

In [14]:
type(c[0])

numpy.int32

In [20]:
a=np.zeros((2,3,4), dtype='int')
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [21]:
a=np.ones((2,3))

In [22]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
arr=np.full((3,3),'abc')

In [26]:
arr

array([['abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc']], dtype='<U3')

In [29]:
arr1=np.random.random((2,3))
arr1

array([[0.77542697, 0.00588064, 0.35424547],
       [0.26940053, 0.33430537, 0.30832815]])

In [28]:
arr1

array([[0.44800807, 0.66195376, 0.75340916],
       [0.83940271, 0.18483204, 0.69776767]])

In [43]:
arr2=np.random.randint((2,4))
arr2

array([1, 2])

In [36]:
arr2

array([1, 1])

In [45]:
d1=np.random.randint(1,50,(4,4))
print(d1)

[[46 18  2 34]
 [43 28 24 37]
 [10 42 26 42]
 [17 36 21 13]]


In [38]:
d1

array([[6, 7, 4, 1],
       [2, 7, 6, 2]])

In [54]:
a1=np.arange(1,7,2)
a1

array([1, 3, 5])

In [58]:
a2=np.linspace(1,10,4)
a2

array([ 1.,  4.,  7., 10.])

### a2

In [61]:
a1=np.arange(0,6)
a1

array([0, 1, 2, 3, 4, 5])

In [62]:
a1.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
arr1 = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
arr1

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 0, 1]])

In [64]:
arr1.reshape((2,6))

array([[1, 2, 3, 4, 5, 2],
       [4, 2, 1, 2, 0, 1]])

In [72]:
a=arr1.reshape((2,2,3))


In [67]:
arr1.size

12

In [68]:
arr1.dtype

dtype('int32')

In [73]:
a.ndim

3

In [74]:
a

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [76]:
a=np.array([[[1,4,7],[2,9,7]],
            [[1,5,8],[3,6,9]]])

In [77]:
a

array([[[1, 4, 7],
        [2, 9, 7]],

       [[1, 5, 8],
        [3, 6, 9]]])

In [78]:
a.ndim

3

In [ ]:
(x,y,z)

In [79]:
a=(['a','b','c','d','e','f','g','h','i','j'])

In [80]:
a[0]

'a'

In [81]:
a[4]

'e'

In [84]:
a[0:4]

['a', 'b', 'c', 'd']

In [85]:
a[0:4:2]

['a', 'c']

In [86]:
a[:3]

['a', 'b', 'c']

In [87]:
a[-1]

'j'

In [89]:
a[-4:-1]

['g', 'h', 'i']

In [90]:
array = np.array([['a1','b1','c1','d1','e1'],
                 ['a2','b2','c2','d2','e2'],
                 ['a3','b3','c3','d3','e3'],
                 ['a4','b4','c4','d4','e4']]
                 
                )

In [93]:
array[1:3,2:4]

array([['c2', 'd2'],
       ['c3', 'd3']], dtype='<U2')

In [97]:
array[2,:]

array(['a3', 'b3', 'c3', 'd3', 'e3'], dtype='<U2')

In [96]:
array[:,3]

array(['d1', 'd2', 'd3', 'd4'], dtype='<U2')

In [98]:
array[2,2]

'c3'

In [99]:
array[::2,::2]

array([['a1', 'c1', 'e1'],
       ['a3', 'c3', 'e3']], dtype='<U2')

In [100]:
array[-3:-1,:]

array([['a2', 'b2', 'c2', 'd2', 'e2'],
       ['a3', 'b3', 'c3', 'd3', 'e3']], dtype='<U2')