In [1]:
import pandas as pd
import numpy as np

# Dataframe

### Creating a dataframe

In [176]:
#Using csv
df=pd.read_csv("weather_data.csv")

In [178]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [11]:
# using excel
df=pd.read_excel("weather_data.xlsx","Sheet1")
df

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [12]:
#Using a dictionary
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}
df = pd.DataFrame(weather_data)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [15]:
#Using a list 
weather_data = [
    ['1/1/2017',32,6,'Rain'],
    ['1/2/2017',35,7,'Sunny'],
    ['1/3/2017',28,2,'Snow']
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [16]:
# Using a tuple
weather_data = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [17]:
#Using a list of dictionaries
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

### Examining data frame

In [127]:
# Display top rows
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [42]:
#Display bottom rows
df.tail()

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [128]:
#Display specified number of rows
df.head(3)

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [44]:
#Display specific rows
df[2:5]

day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [28]:
#Information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   day          6 non-null      object
 1   temperature  6 non-null      int64 
 2   windspeed    6 non-null      int64 
 3   event        6 non-null      object
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes


In [65]:
#Names of the columns
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [30]:
#Display the number of rows and columns
df.shape

(6, 4)

In [31]:
#Display statistical properties of all the numerical columns in the dataframe
df.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [39]:
#Display unique values in a column
df['event'].unique

<bound method Series.unique of 0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object>

In [40]:
df.to_string()

'        day  temperature  windspeed  event\n0  1/1/2017           32          6   Rain\n1  1/2/2017           35          7  Sunny\n2  1/3/2017           28          2   Snow\n3  1/4/2017           24          7   Snow\n4  1/5/2017           32          4   Rain\n5  1/6/2017           31          2  Sunny'

In [48]:
#Display rows where a condition is satisfied
df[df['temperature']==32]

day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [129]:
df['temperature']==32

0     True
1    False
2    False
3    False
4     True
5    False
Name: temperature, dtype: bool

In [199]:
df[['temperature','event']]

temperature  event
0           32   Rain
1           35  Sunny
2           28   Snow
3           24   Snow
4           32   Rain
5           31  Sunny

In [201]:
df[df['event'].isin(['Snow','Sunny'])]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
5  1/6/2017           31          2  Sunny

In [52]:
#Display index
df.index

RangeIndex(start=0, stop=6, step=1)

In [54]:
#Setting index
df.set_index('temperature')

day  windspeed  event
temperature                            
32           1/1/2017          6   Rain
35           1/2/2017          7  Sunny
28           1/3/2017          2   Snow
24           1/4/2017          7   Snow
32           1/5/2017          4   Rain
31           1/6/2017          2  Sunny

In [55]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [56]:
df.set_index('temperature',inplace=True)

In [57]:
df

day  windspeed  event
temperature                            
32           1/1/2017          6   Rain
35           1/2/2017          7  Sunny
28           1/3/2017          2   Snow
24           1/4/2017          7   Snow
32           1/5/2017          4   Rain
31           1/6/2017          2  Sunny

In [59]:
df.loc[32]

day  windspeed event
temperature                           
32           1/1/2017          6  Rain
32           1/5/2017          4  Rain

### Read write excel csv

In [84]:
#Reading csv as it is
df=pd.read_csv("stock_data.csv")
df

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [89]:
#reading csv leaving few rows
df=pd.read_csv("stock_data.csv",skiprows=2)
df

WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1  RIL   not available   50  1023  mukesh ambani
2  TATA            5.6   -1  n.a.     ratan tata

In [93]:
#Reading from a specified row as header
df=pd.read_csv("stock_data.csv",header=3)
df

MSFT             -1  85    64     bill gates
0  RIL   not available  50  1023  mukesh ambani
1  TATA            5.6  -1  n.a.     ratan tata

In [95]:
#When we dont have column names, we can use this to give names to columns
df=pd.read_csv("stock_data.csv",skiprows=0,header=None,names=["col1","col2","col3","col4","col5"])
df

col1           col2     col3   col4           col5
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4     RIL   not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

Skiprows will skip few rows, header will tell which row to select as header. When we dont have column names, we can give header as none and give column names

In [98]:
#Read specified number of rows
df=pd.read_csv("stock_data.csv",nrows=3)
df

tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [97]:
df=pd.read_csv("stock_data.csv")
df

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

We can see that there are invalid values in the data. We can change the null values while importing

In [99]:
df = pd.read_csv("stock_data.csv", na_values=["n.a.", "not available"])
df

tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [101]:
#Replace invalid values with NaN for entire dataframe
df = pd.read_csv("stock_data.csv", na_values=["n.a.", "not available",-1])
df

tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [102]:
#Replace invalid values as per customisation
df = pd.read_csv("stock_data.csv",  na_values={
        'eps': ['not available'],
        'revenue': [-1],
        'people': ['not available','n.a.']
    })
df

tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [108]:
#Write to csv along with index
df.to_csv("new.csv")

In [114]:
#Write to csv without index
df.to_csv("new.csv",index=False)

In [109]:
#Write only specific columns into csv
df.to_csv("new.csv", columns=["tickers","price"], index=False)

In [113]:
#Write without header and index
df.to_csv("new.csv",header=False, index=False)

#### From excel

In [115]:
df = pd.read_excel("stock_data.xlsx","Sheet1")
df

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [116]:
#leaves two columns and 1 row in excel sheet 
df.to_excel("new.xlsx", sheet_name="stocks", index=False, startrow=2, startcol=1)

Writing multiple dataframes to a excel

In [122]:
df=pd.read_csv("weather_data.csv")
df1=df=pd.read_csv("stock_data.csv")


In [123]:
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
    df1.to_excel(writer, sheet_name="stocks")
    df.to_excel(writer, sheet_name="weather")

## Null Value Interpretation

In [134]:
dfNull=pd.read_csv("weather_data_null.csv") 
dfNull

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [137]:
type(dfNull['day'][0])

str

In [142]:
dfNull = pd.read_csv("weather_data_null.csv",parse_dates=['day'])
dfNull

day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [143]:
type(dfNull.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [144]:
#Changing the index
dfNull.set_index('day',inplace=True)
dfNull

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

###### Drop rows with null values

In [145]:
dfNull.dropna()

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

###### Fill all NaN with one specific value

In [148]:
new_df = dfNull.fillna(0)
new_df

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          0.0        9.0   Sunny
2   1/5/2017         28.0        0.0    Snow
3   1/6/2017          0.0        7.0       0
4   1/7/2017         32.0        0.0    Rain
5   1/8/2017          0.0        0.0   Sunny
6   1/9/2017          0.0        0.0       0
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

###### Fill na using column names and dict

In [150]:
new_df = dfNull.fillna({
        'temperature': 0,
        'windspeed': 0,
        'event': 'No Event'
    })
new_df

day  temperature  windspeed     event
0   1/1/2017         32.0        6.0      Rain
1   1/4/2017          0.0        9.0     Sunny
2   1/5/2017         28.0        0.0      Snow
3   1/6/2017          0.0        7.0  No Event
4   1/7/2017         32.0        0.0      Rain
5   1/8/2017          0.0        0.0     Sunny
6   1/9/2017          0.0        0.0  No Event
7  1/10/2017         34.0        8.0    Cloudy
8  1/11/2017         40.0       12.0     Sunny

###### Use method to determine how to fill na values forwardfill or backward fill

In [157]:
# new_df = df.fillna(method="ffill")
new_df=dfNull.ffill()
new_df

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        7.0   Sunny
6   1/9/2017         32.0        7.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [159]:
new_df = df.fillna(method="bfill")
# new_df=dfNull.bfill()
new_df

temperature  windspeed   event
day                                       
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

###### Use of axis to fill 

In [160]:
new_df = dfNull.fillna(method="bfill", axis="columns") # axis is either "index" or "columns"
new_df

day temperature windspeed   event
0   1/1/2017        32.0       6.0    Rain
1   1/4/2017         9.0       9.0   Sunny
2   1/5/2017        28.0      Snow    Snow
3   1/6/2017         7.0       7.0     NaN
4   1/7/2017        32.0      Rain    Rain
5   1/8/2017       Sunny     Sunny   Sunny
6   1/9/2017         NaN       NaN     NaN
7  1/10/2017        34.0       8.0  Cloudy
8  1/11/2017        40.0      12.0   Sunny

In [164]:
new_df = dfNull.fillna(method="ffill", axis="columns") # axis is either "index" or "columns"
new_df

day temperature windspeed     event
0   1/1/2017        32.0       6.0      Rain
1   1/4/2017    1/4/2017       9.0     Sunny
2   1/5/2017        28.0      28.0      Snow
3   1/6/2017    1/6/2017       7.0       7.0
4   1/7/2017        32.0      32.0      Rain
5   1/8/2017    1/8/2017  1/8/2017     Sunny
6   1/9/2017    1/9/2017  1/9/2017  1/9/2017
7  1/10/2017        34.0       8.0    Cloudy
8  1/11/2017        40.0      12.0     Sunny

In [165]:
#limit Parameter
new_df = dfNull.fillna(method="ffill",limit=1)
new_df

day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        9.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         32.0        NaN   Sunny
6   1/9/2017          NaN        NaN   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [169]:
df=pd.read_csv("stock_data.csv")
df

tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

###### Replace

In [170]:
#Replacing a single valie
#
new_df = df.replace('not available', value=np.NaN)
new_df

tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65           n.a.
2    MSFT     -1       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA    5.6       -1  n.a.     ratan tata

In [172]:
#Replacing a set of values
# 
new_df = df.replace(to_replace=['not available','n.a.'], value=np.NaN)
new_df

tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65            NaN
2    MSFT     -1       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA    5.6       -1   NaN     ratan tata

In [175]:
#Replace per column basis
new_df = df.replace({
        'eps': 'not available',
        'price': 'n.a.',
        'people': 'n.a.'
    }, np.nan)
new_df

tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65            NaN
2    MSFT     -1       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA    5.6       -1   NaN     ratan tata

###### Group By function

In [47]:
df = pd.read_csv("weather_by_cities.csv")
df

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [48]:
#Groupby will create a object 
g = df.groupby("city")
g

In [50]:
g.get_group('mumbai')

day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [14]:
#Accessing a group
g.get_group('new york')['temperature']

0    32
1    36
2    28
3    33
Name: temperature, dtype: int64

In [11]:
g.sum()

temperature  windspeed
city                            
mumbai            354         37
new york          129         32
paris             191         51

In [56]:
g.get_group('mumbai').index

Int64Index([4, 5, 6, 7], dtype='int64')

In [61]:
#Using statistics on group
g.mean()

temperature  windspeed
city                            
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [73]:
g.get_group('mumbai').describe()

temperature  windspeed
count     4.000000   4.000000
mean     88.500000   9.250000
std       3.109126   5.057997
min      85.000000   5.000000
25%      86.500000   5.000000
50%      88.500000   8.500000
75%      90.500000  12.750000
max      92.000000  15.000000

# Series


In [74]:
#Creating an empty Series
s=pd.Series()
print(s)

Series([], dtype: float64)


C:\Users\LENOVO\AppData\Local\Temp/ipykernel_6872/2242303654.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s=pd.Series()


In [80]:
#Creating using an array
a=np.array([1,2,3,4])
s1=pd.Series(a)
print(s1)

0    1
1    2
2    3
3    4
dtype: int32


In [79]:
#Creating Series using an array with custom index
s2=pd.Series(a,index=['a','b','c','d'])
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [86]:
#Creating Series from a List
b=["Hello","Numpy","Ninja"]
s3=pd.Series(b)
print(s3)

0    Hello
1    Numpy
2    Ninja
dtype: object


In [87]:
dict1= {'a':0,'b':1,'c':2}
s4=pd.Series(dict1)
print(s4)

a    0
b    1
c    2
dtype: int64


In [88]:
# Creating from a scalar value

g = pd.Series(10, index =[0, 1, 2, 3,4,5])
print(g)

0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64


In [108]:
#Creating using functions
h=pd.Series(np.arange(1,10,2))
print(h)

0    1
1    3
2    5
3    7
4    9
dtype: int32


In [97]:
#Accesing the Series
l1=list("NumpyNinja")
l1
ser=pd.Series(l1)
print(ser)

0    N
1    u
2    m
3    p
4    y
5    N
6    i
7    n
8    j
9    a
dtype: object


In [118]:
#Accessing Using location
ser[:5]

0    N
1    u
2    m
3    p
4    y
dtype: object

In [119]:
# Access using Index
print(ser[7])

n


In [104]:
ser1 = pd.Series(l1,index=np.arange(11,21))

In [105]:
ser1

11    N
12    u
13    m
14    p
15    y
16    N
17    i
18    n
19    j
20    a
dtype: object

In [106]:
ser1.head()

11    N
12    u
13    m
14    p
15    y
dtype: object

In [115]:
h.index=['a','b','c','d','e']
print(h)

a    1
b    3
c    5
d    7
e    9
dtype: int32


In [113]:
h.reset_index()

index  0
0     a  1
1     b  3
2     c  5
3     d  7
4     e  9

In [117]:
h.reset_index(drop=True)

0    1
1    3
2    5
3    7
4    9
dtype: int32

In [129]:
print(s2)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             -
print("\n",s2.loc['c'])
print("\n",s2.iloc[3])

a    1
b    2
c    3
d    4
dtype: int64

 3

 4


In [107]:
df.index

RangeIndex(start=0, stop=768, step=1)

In [114]:
ser1=pd.Series(data=data['EMPID'])

In [115]:
ser1

0    101.0
1    102.0
2    103.0
3    104.0
4      NaN
5      NaN
6    107.0
7    108.0
dtype: float64

In [113]:
data['EMPID']

[101, 102, 103, 104, nan, nan, 107, 108]

# NUMPY

In [46]:
#creating a numpy array from a list
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [93]:
#creating array from tuple
arrTup=np.array(('x','y','z'))
arrTup

array(['x', 'y', 'z'], dtype='<U1')

In [39]:
#creating array of zeros
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
#creating array of 1's
b=np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
#creating array with a single value
c=np.full((3,3),5)
c

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [100]:
#creating array with random values
d=np.random.random((2,3))
d

array([[0.22773462, 0.24735065, 0.71487004],
       [0.21422703, 0.38673901, 0.08742929]])

In [38]:
#creating using random integer values in given range
d1=np.random.randint(1,10,(2,4))
print(d1)

[[3 8 2 2]
 [9 2 6 1]]


In [3]:
#creating array with step size arange(start,end,step)
e=np.arange(1,10,2)
e

array([1, 3, 5, 7, 9])

In [33]:
#creating array with equal spacing
f=np.linspace(1,10,5)
f

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [37]:
len(f)

5

In [38]:
# Reshaping 3X4 array to 2X2X3 array
arr1 = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
 
newarr = arr1.reshape(3,2,2)
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 2],
        [4, 2]],

       [[1, 2],
        [0, 1]]])

In [119]:
#Get Dimension
newarr.ndim

3

In [123]:
# Getting shape
a.shape

(2, 3)

In [127]:
# Get Type
arr1.dtype

dtype('int32')

In [39]:
#Getting number of elements
newarr.size

12

In [40]:
len(newarr)

3

# Array Slicing


In [33]:
array = np.array([['a1','b1','c1','d1','e1'],
                 ['a2','b2','c2','d2','e2'],
                 ['a3','b3','c3','d3','e3'],
                 ['a4','b4','c4','d4','e4']]
                 
                )

In [74]:
array

array([['a1', 'b1', 'c1', 'd1', 'e1'],
       ['a2', 'b2', 'c2', 'd2', 'e2'],
       ['a3', 'b3', 'c3', 'd3', 'e3'],
       ['a4', 'b4', 'c4', 'd4', 'e4']], dtype='<U2')

In [17]:
# Get a specific element [r,c]
array[0,1]

'b1'

In [20]:
array[-1,-2]

'd4'

In [133]:
#Get a specific row
array[3,:]

array(['a4', 'b4', 'c4', 'd4', 'e4'], dtype='<U2')

In [134]:
#Get a specific Column
array[:,2]

array(['c1', 'c2', 'c3', 'c4'], dtype='<U2')

In [135]:
#Get using [startindex:stopindex:stepsize]
array[::2,::3]

array([['a1', 'd1'],
       ['a3', 'd3']], dtype='<U2')

In [132]:
array[:,2:]

array([['c1', 'd1', 'e1'],
       ['c2', 'd2', 'e2'],
       ['c3', 'd3', 'e3'],
       ['c4', 'd4', 'e4']], dtype='<U2')

In [116]:
array[::2, ::3]

array([['a1', 'd1'],
       ['a3', 'd3']], dtype='<U2')

In [27]:
array[-3:-1,:]

array([['a2', 'b2', 'c2', 'd2', 'e2'],
       ['a3', 'b3', 'c3', 'd3', 'e3']], dtype='<U2')

# Basic operations on Numpy

In [51]:
oArr=np.array([[1,2,3],
     [4,5,6],
     [7,8,9]])

In [52]:
np.sum(oArr,axis=0)

array([12, 15, 18])

In [7]:
#Addition in array
oArr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
#Multiplication
oArr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
# Dividing with 2
oArr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [10]:
# Sum along axis down the rows
np.sum([[1,2],[3,4]], axis=0)

array([4, 6])

In [11]:
# Sum along axis down the columns
np.sum([[1,2],[3,4]], axis=1)

array([3, 7])

In [15]:
#Adding 2 arrays
a=np.arange(1,6).reshape(1,5)
print(a)
b=np.linspace(1,15,15).reshape(3,5)
print(b)

[[1 2 3 4 5]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


In [16]:
np.add(a,b)

array([[ 2.,  4.,  6.,  8., 10.],
       [ 7.,  9., 11., 13., 15.],
       [12., 14., 16., 18., 20.]])

In [32]:
a1=np.random.randint(1,10,(2,5))
print(a1)
b1=np.random.randint(11,30,(2,5))
print(b1)
print(np.add(a1,b1))

[[6 2 6 7 8]
 [9 3 8 6 4]]
[[27 20 19 29 25]
 [16 18 14 11 22]]
[[33 22 25 36 33]
 [25 21 22 17 26]]


In [12]:
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])

In [13]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [9, 6, 0]])

In [14]:
print(a.T)

[[1 3 9]
 [2 4 6]
 [3 5 0]]


In [30]:
#Maximum element in an array
print ("Largest element is:", a.max())
print ("Row-wise maximum elements:",
                    a.max(axis = 1))
print ("Column-wise maximum elements:",
                    a.max(axis = 0))

Largest element is: 9
Row-wise maximum elements: [3 5 9]
Column-wise maximum elements: [9 6 5]


In [32]:
#Minimum element in an array
print ("Smallest element is:", a.min())
print ("Row-wise Minimum elements:",
                    a.min(axis = 1))
print ("Column-wise Minimum elements:",
                    a.min(axis = 0))

Smallest element is: 0
Row-wise Minimum elements: [1 3 0]
Column-wise Minimum elements: [1 2 0]


In [12]:
#Sorting of Array
a = np.array([[1, 4, 2],
                 [3, 4, 6],
              [0, -1, 5]])
print("Array\n",a)
print ("Array elements in sorted order:\n",np.sort(a, axis = None))
print("Sorted array\n" , np.sort(a))
# sort array row-wise
print ("Column-wise sorted array:\n",
                np.sort(a, axis = 0))


Array
 [[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]
Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Sorted array
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column-wise sorted array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


Be careful when copying array

In [47]:
abcd=([1,2,3])
print(abcd)

[1, 2, 3]


In [44]:
dcba=abcd
print(dcba)

[1, 2, 3]


In [46]:
dcba[2]=30
print(dcba)
print(abcd)

[1, 2, 30]
[1, 2, 30]


In [49]:
dcba=abcd.copy()
print(dcba)
print(abcd)
dcba[2]=20
print(dcba)
print(abcd)

[1, 2, 3]
[1, 2, 3]
[1, 2, 20]
[1, 2, 3]


# Stacking and Splitting 

In [13]:
a = np.array([[1, 2],
              [3, 4]])
  
b = np.array([[5, 6],
              [7, 8]])

In [16]:
#Vertical Stacking stacks one above other
print('Vertical Stacking',np.vstack((a,b)))

Vertical Stacking [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
#Horizontal Stacking, stacks one beside other
print('Horizontal Stacking',np.hstack((a,b)))

Horizontal Stacking [[1 2 5 6]
 [3 4 7 8]]


In [22]:
#Column Stacking
c=np.array([9,10])
print('Column Stacking',np.column_stack((a,c)))

Column Stacking [[ 1  2  9]
 [ 3  4 10]]


In [24]:
#Concatenate
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1))
print("\nConcatenating to 1st axis:\n", np.concatenate((a, b), 0))


Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]

Concatenating to 1st axis:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
# Splitting 
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [46]:
# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 2, 3],
       [7, 8, 9]]), array([[ 4,  5,  6],
       [10, 11, 12]])]


In [43]:
#Horizontal splitting on specified position
np.hsplit(a,np.array([2,3,5]))

[array([[1, 2],
        [7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]]),
 array([[ 6],
        [12]])]

In [34]:
#Vertical Split
print("Splitting along Vertical axis into 2 parts:\n", np.vsplit(a, 2))

Splitting along Vertical axis into 2 parts:
 [array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


In [44]:
#Horizontal splitting on specified position
np.vsplit(a,np.array([2,3,5]))

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([], shape=(0, 6), dtype=int32),
 array([], shape=(0, 6), dtype=int32),
 array([], shape=(0, 6), dtype=int32)]

In [35]:
# Splitting along axis
print("Splitting along specified axis into 2 parts:\n", np.split(a, 2))

Splitting along specified axis into 2 parts:
 [array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


In [40]:
print("Splitting along specified axis into 2 parts:\n", np.array_split(a, 3,axis=1))

Splitting along specified axis into 2 parts:
 [array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
